<?php

namespace App\Filament\Cam\Resources\Cameras;

use app\Models\Camera;
use BackedEnum;
use Filament\Resources\Resource;
use Filament\Schemas\Schema;
use Filament\Support\Icons\Heroicon;

class CameraResource extends Resource
{
    protected static ?string $model = Camera::class;

    protected static string|BackedEnum|null $navigationIcon = Heroicon::OutlinedRectangleStack;

    protected static ?string $recordTitleAttribute = 'name';

   public static function infolist(Schema $schema): Schema
   {
       return parent::infolist($schema); // TODO: Change the autogenerated stub
   }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }
}
